nelmio_cors:
    paths:
        '^/':
            allow_origin: ['http://localhost:8080']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'OPTIONS', 'GET', 'PUT', 'DELETE']
            max_age: 3600
