when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
# config/routes.yaml
api_data:
  path: /api/data
  controller: App\Controller\ApiController::fetchData
